### ISSUE TITLE
Question with spring 

### ISSUE THREAD

**Issue by kntmrkm** [railsware/global#15]
When using this gem with spring.
It seems need to stop spring once.
After spring reloaded. New setting value can be use in app.

Must I stop spring once? Any setting need?

**Comment by le0pard** [comment]
Maybe this can help?

```ruby
Spring.before_fork do
  Global.reload!
end
```

**Comment by kntmrkm** [comment]
Thanks!
It became better.

Best way is reload without Rails server.
Can I do that?

**Comment by le0pard** [comment]
`Global.reload!` is reload configuration. I am not sure, how rails server interconnected here

**Comment by kntmrkm** [comment]
OK. I will try later with tips like `http://crypt.codemancers.com/posts/2013-10-03-rails-reloading-in-dev-mode/`. Thanks lot!
