### ISSUE TITLE
Deprecated processor interface

### ISSUE THREAD

**Issue by bluewomble** [railsware/global#16]
When I use the global gem from with Rails (using Rails 4.1.16), I get the following error (I'm using sprockets_3.7.1):

DEPRECATION WARNING: You are using the a deprecated processor interface #<Proc:0x00000007111a78@~/.rvm/gems/ruby-2.2.1/gems/global-0.1.2/lib/global/engine.rb:10>.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors

Am I doing something wrong, or does Global need to be updated?

Thanks.

**Comment by le0pard** [comment]
@bluewomble Global is not migrated to new sprockets interface. You can make PR.

**Comment by le0pard** [comment]
@bluewomble this PR should fix this problem: https://github.com/railsware/global/pull/20 You can check from branch

**Comment by le0pard** [comment]
@bluewomble should be fixed in 0.2.0 version

**Comment by bluewomble** [comment]
Brilliant - thanks!
