### ISSUE TITLE
generate_js creates empty Global object

### ISSUE THREAD

**Issue by babgyy** [railsware/global#19]
Hi, thanks for this gem, it's precisely what I was looking for

I have an issue setting it up, though.
I have followed instructions to set it up (required global-js in application.js, created global.rb in initializers folder, and added YAML files in config/global) 
From Rails Console, `Global.configuration` reads correctly the values, but from Javascript Console, the Global object exists but is empty.
I am using Global gem 0.1.2 and Rails 4.2.4

Rails console
```
> Global.configuration
=> {"hosts"=>{"toto"=>"dev"}}
```

Javascript console
```
> JSON.stringify(Global)
=> "{}"
```

And indeed using directly the command `Global.generate_js` yields an empty Global object: 
Rails console
```
> Global.generate_js
=> "window.Global = {}"
```

app/config/global/hosts.yml
```
default: 
  toto: "tata"
development:
  toto: "dev"
staging: 
  toto: "staging"
production:
  toto: production
```

app/config/initializers/global.rb
```
Global.configure do |config|
  config.environment = Rails.env.to_s
  config.config_directory = Rails.root.join('config/global').to_s
end
```

Anything I am missing ? 
Thanks in advance

**Comment by le0pard** [comment]
@babgyy you miss configuration section https://github.com/railsware/global/blob/master/README.md#configuration-1 Read it

**Comment by babgyy** [comment]
Sorry about that !
That fixed it
Thanks for your prompt answer
