### ISSUE TITLE
Global with Sinatara app

### ISSUE THREAD

**Issue by rakesh-1010** [railsware/global#22]
I am trying to setup global with a sinatara app,
In my app.rb file i have initialized the settings as
```
Global.environment => Sinatra::Base.environment
Global.config_director=>settings.root+"config/global"
```
I have created a `mailer.yml` file inside `config/global`
Contents of `mailer.yml` looks like
```
development:
    from_email: 'example@mail.com'
    bcc_email: 'example@mail.com'
```
but when i do `Global.mailer` in sinatara console it returns an empty hash `{}`, i also tried without the environment see below but it still return empty hash 
```
from_email: 'example@mail.com'
bcc_email: 'example@mail.com'
```
Are there any additional configuration with sinatara that I am missing?

**Comment by le0pard** [comment]
Add to `mailer.yml` key `default` and check again. If in this case you will get keys from `default`, this mean, that your environment is not `development`.

**Comment by rakesh-1010** [comment]
yes the default key is working, but no other keys seem to work
But  `Global.environment` returns `:development`

**Comment by le0pard** [comment]
`Global.environment` should contain string, not symbol.

**Comment by rakesh-1010** [comment]
Ok,  that seems to be the issue thanks
