### ISSUE TITLE
Problem in loading Global file

### ISSUE THREAD

**Issue by ara-wtag** [railsware/global#23]
Suppose we have a file `name.yml` under Global directory as follow

`default:
  host: <%= ENV.fetch('TRAVEL_HOST') %>

test:
  host: <%= ENV.fetch('TRAVEL_HOST', 'example.com') %>

development:
  host: <%= ENV.fetch('TRAVEL_HOST', 'example.com') %>

staging:
production: `

My purpose is when I will run from localhost as development, I will not provide any value in `.env` file as I am giving value `example.com`. But In such way unable to run rails server or rails console, as it shows 'WELLTRAVEL_HOST' key is missing at .`env` file.

My question is why it is not possible, as at my development environment  section default environment is overridden and in that sense it should allow to run rails server.

Can you please provide some way forward so that I can provide value in .env file only in production and staging  environment but not in development and test.

**Comment by le0pard** [comment]
This `default` keys should have ability to be executed without errors to be merged later with keys from env. In your example, this will not work without `WELLTRAVEL_HOST` env variable for any environment.

**Comment by ara-wtag** [comment]
soved
