### ISSUE TITLE
Commented out YAML is still being evaluated

### ISSUE THREAD

**Issue by ddi-wtag** [railsware/global#32]
## Background

```shell
# config/settings/service.yml
#   This is commented code: url: <%= ENV.fetch('RANDOM_STUFF') %>
default:
  url: https://www.google.com

development:
production:
```

## Expected behaviour

Global should just load that file, without caring about what's in the comments.

## Actual behaviour

```ruby
irb(main):009:0> Global.service.url
Traceback (most recent call last):
        4: from (irb):9
        3: from (irb):9:in `rescue in irb_binding'
        2: from (erb):1:in `<main>'
        1: from (erb):1:in `fetch'
KeyError (key not found: "RANDOM_STUFF")
```

## Thoughts

I suspect that the `erb` is parsed first, then the `YAML`...

**Comment by le0pard** [comment]
> I suspect that the erb is parsed first, then the YAML...

Yes, it is exactly how it works - https://github.com/railsware/global/issues/31#issuecomment-524366468

This is because you can write in yaml like this:

```yaml
default:
<% ['one', 'two', 'three'].each do |key| %>
  <%= key %>Test: <%= get_some_val(key) %>
<% end %>
```

**Comment by ddi-wtag** [comment]
Hey @le0pard,

Thanks for your replies.

It make sense to me...thanks a lot for explaining these!
