### ISSUE TITLE
An empty yml file in the config dir causes exception even in good yml files

### ISSUE THREAD

**Issue by davidlbean** [railsware/global#34]
To reproduce:

1.  Setup as per instructions in the README.
2.  Populate the global directory with a hosts.yml file and an aws.yml file.  These files should have entries for development, staging, test, and production environments.
3.  Referencing Global.hosts and Global.aws works just fine.
4.  Add a new file, version.yml, to the global directory.  Leave the version.yml file empty.
5.  Referencing Global.hosts, Global.aws, now throws global-1.1.0/lib/global/base.rb:84:in `get_config_by_key': undefined method `[]' for nil:NilClass (NoMethodError).
6.  Remove the empty version.yml file and retry...works just fine now.

This isn't a critical issue because one shouldn't have an empty file in there anyway, eh?  But, I didn't realize what I had done, and it took me a long time to track down what the problem was.  Maybe a warning on load that a config file isn't correct?  

Super gem, btw.  Thanks for writing it!  If I get really ambitious, I'll pull the repo and see if I can contribute a fix for this.

**Comment by le0pard** [comment]
@davidlbean thanks for report. I added fix, it should be released with 2.0 - https://github.com/railsware/global/pull/35

**Comment by le0pard** [comment]
Fixed in v2.0.0
