### ISSUE TITLE
Configurations in config directory cannot be easily overridden

### ISSUE THREAD

**Issue by cyu** [railsware/global#43]
With the filesystem backend, because configs from the `global` directory overrides the `global.yml` and the `global.environment.yml`, you can't easily override values that are defined in YAML files under global.

What should happen is that the environment files should be loaded after the directory files.  This way, someone can implement a `global.development.yml` to override configs for their development environment.

**Comment by le0pard** [comment]
https://github.com/railsware/global#environment-files - based on doc env files loaded after non-env files. So not clear the issue. Can you create test or give example with files?

**Comment by cyu** [comment]
@le0pard Apologies – I tested the scenario and review the code before filing the ticket, but must not have tested correctly because I it's working now.
