### ISSUE TITLE
Returning empty object

### ISSUE THREAD

**Issue by lpender** [railsware/global#44]
Hi, thank you for the gem.

My experience seems to directly contradict the documentation, unfortunately.

config/initializers/global.rb
```
Global.configure do |config|
  config.backend :filesystem
end
```

config/global/site.yml
```
name: Stikki
prismic_subdomain: thought
```

Rails console:

```
[8] pry(main)> Global.site
=> {}
```

Thanks

**Comment by le0pard** [comment]
Ok, lest check README:

```ruby
config.backend :filesystem, environment: "YOUR_ENV_HERE", path: "PATH_TO_DIRECTORY_WITH_FILES"
```

In your example I did not see `environment` and `path` key. For rails env it will fallback to:

```ruby
config.backend :filesystem, environment: Rails.env.to_s, path: Rails.root.join('config', 'global').to_s
```

In local rails env it will have `environment: "development"`. This mean, it will use `development` or `default` section in files. In your example file `site.yml` have no such sections. So it should be empty - exactly what we get `Global.site == {}`

**Comment by leonid-shevtsov** [comment]
So, to summarize, the `config/global/site.yml` should look like:

```yaml
default:
  name: Stikki
  prismic_subdomain: thought
```

HTH
